ENGR00220169: imx6: Fix build break when make modules
Fix the following build errors:

 Building modules, stage 2.
 MODPOST 33 modules
ERROR: "prp_vf_sdc_deselect_bg"
[drivers/media/video/mxc/capture/mxc_v4l2_capture.ko] undefined!
ERROR: "foreground_sdc_deselect"
[drivers/media/video/mxc/capture/mxc_v4l2_capture.ko] undefined!
ERROR: "prp_vf_sdc_select_bg"
[drivers/media/video/mxc/capture/mxc_v4l2_capture.ko] undefined!
ERROR: "foreground_sdc_select"
[drivers/media/video/mxc/capture/mxc_v4l2_capture.ko] undefined!
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2

The break reason is the *_defconfig has not updated accordingly as
Kconfig file changed which results in the modules dependency confusion.

Remove the problemtic module -- CAMERA in defconfig, since imx6s has
no CAMERA driver support yet and imx6q update defconfig does not need
it at all.

Signed-off-by: Robby Cai <R63905@freescale.com>